---
title: "NMDS-May"
author: "Jiashu Chen"
format: pdf
editor: visual
---

## NMDS Exploratory Analysis For May Habitat Sites

### 

```{r, warning=FALSE, message=FALSE}
# Load Packages
library(tidyverse)
library(vegan)
library(lubridate)
# Set Working Directory
setwd("/Users/jiashuchen/salmon-research/sp23-salmon-research/analysis")

```

```{r, warning=FALSE, message=FALSE}
# Load Data Sets
lag21_hab_may_oct <- read_csv("LAG21_Habitat_May_Oct.csv")
lag21_shelter <- read_csv("LAG21_InstreamShelter.csv")

#Filter to retain only May sites
#Clean up data, calculate Vol, max_temp, max_do, max_vel, max_rctdepth
lag21_hab_may_oct[7, 2] = '02/05/21' 

#Remove space and parentheses
names(lag21_hab_may_oct)<-str_replace_all(names(lag21_hab_may_oct), c(" " = "", "\\(DD/MM/YY\\)" = ""))
#Remove space and parentheses
names(lag21_shelter)<-str_replace_all(names(lag21_shelter), c(" " = "", "\\(0\\-3\\)" = ""))


#Clean up data and select useful data columns
###Replaced na with 0###
clean_lag21_hab_shelter <- lag21_hab_may_oct  %>% 
  drop_na(Date) %>%
  mutate(Date = dmy(Date)) %>% 
  mutate(Month = month(Date),
         Month = case_when(
           Month == 4 ~ 5,
           TRUE ~ Month
         )) %>% 
  filter(Month == 5) %>% 
  rowwise() %>% 
  mutate(Max_vel = max(c_across(c(Vel0_ms, 
                                  Vel1_ms, 
                                  Vel2_ms, 
                                  Vel3_ms, 
                                  Vel4_ms, 
                                  Vel5_ms)), 
                       na.rm = T)) %>%
  mutate(across(c(Width3_m, Length_m), as.double)) %>% 
  ###Change 31 of may to 1 of june; repeat any empty length with previous values.###
  mutate(Median_width_m = median(c_across(c(Width0_m, 
                                     Width1_m,
                                     Width2_m, 
                                     Width3_m, 
                                     Width4_m,
                                     Width5_m)),
                          na.rm = T)) %>% 
  mutate(Median_depth_m = median(c_across(c(Depth0_cm, 
                                     Depth1_cm,
                                     Depth2_cm, 
                                     Depth3_cm,
                                     Depth4_cm,
                                     Depth5_cm)),
                          na.rm = T) / 100) %>% 
  mutate(Vol_m3 = Length_m * Median_depth_m * Median_width_m) %>%
  left_join(lag21_shelter, #Use left join to preserve major data rows.
             by = join_by(SiteName == SiteName),
             suffix = c('.hab', '.shelter')) %>%
  mutate(Canopy_total = (Canopy_Head + Canopy_Mid) / 2,  
         DO_Percent = as.double(DO_Percent),
         Temperature_C = as.double(Temperature_C)) %>% 
  select(SiteName, Date, Shelter_Value, 
         Vol_m3, Temperature_C, DO_Percent,
         Max_vel, RCTdepth_cm, Canopy_total) %>% 
  drop_na()
  #%>% 
  #mutate_all(~replace_na(., 0))
view(clean_lag21_hab_shelter)
```

```{r, warning=FALSE, message=FALSE}
#Random Initial Placement NMDS
#Shuffle rows
clean_lag21_hab_shelter <- clean_lag21_hab_shelter[sample(nrow(clean_lag21_hab_shelter)),] 

nmds_data <- clean_lag21_hab_shelter %>% 
  select(-c(SiteName, Date)) %>% as.matrix()

nmds_lag21 <-metaMDS(nmds_data, distance = "bray", k = 2, trymax = 200, plot = F)
nmds_lag21
stressplot(nmds_lag21)





ordiplot(nmds_lag21, type = "n")
orditorp(nmds_lag21, display="species", col='red', air=0.01)
orditorp(nmds_lag21, display="sites", air=0.01)


```
